//Nick Boltralik, 2017
#include "types.h"

//TODO - organize this
char *LAMBDA = "LAMBDA";
char *OPEN_PAREN = "OPEN_PAREN";
char *OPTEXPRESSIONLIST = "OPTEXPRESSIONLIST";
char *CLOSE_PAREN = "CLOSE_PAREN";
// char *BLOCK = "BLOCK"; //TODO - do I need this?
char *STATEMENTLIST = "STATEMENTLIST";
// char *STATEMENT = "STATEMENT"; //TODO - do I need this?
char *FUNCTIONCALL = "FUNCTIONCALL";
char *RUN = "RUN";
char *VARIABLE = "VARIABLE";
char *SEMICOLON = "SEMICOLON";
char *EXPRESSION = "EXPRESSION";
char *IFSTATEMENT = "IFSTATEMENT";
char *WHILELOOP = "WHILELOOP";
// char *VARIABLEDEF = "VARIABLEDEF"; //TODO - do I need this?
// char *ASSIGNMENT = "ASSIGNMENT"; //TODO - do I need this?
// char *UNARY = "UNARY"; //TODO - do I need this?
// char *OPERATOR = "OPERATOR"; //TODO - do I need this?
char *ASSIGN = "ASSIGN";
char *OPEN_SQUARE = "OPEN_SQUARE";
char *CLOSE_SQUARE = "CLOSE_SQUARE";
char *PLUS = "PLUS";
char *MINUS = "MINUS";
char *MULTIPLY = "MULTIPLY";
char *DIVIDE = "DIVIDE";
char *EXPONENTIATE = "EXPONENTIATE";
char *MODULO = "MODULO";
char *LT = "LT";
char *GT = "GT";
char *LT_EQUAL = "LT_EQUAL";
char *GT_EQUAL = "GT_EQUAL";
char *EQUAL = "EQUAL";
char *N_EQUAL = "N_EQUAL";
char *AND = "AND";
char *OR = "OR";
char *NOT = "NOT";
char *INTEGER = "INTEGER";
char *STRING = "STRING";
char *COMMA = "COMMA";
char *INTEGERDEF = "INTEGERDEF";
char *ARRAYDEF = "ARRAYDEF";
char *FUNCTIONDEF = "FUNCTIONDEF";
char *STRINGDEF = "STRINGDEF";
char *NULLDEF = "NULLDEF";
char *DEFINE = "DEFINE";
char *IF = "IF";
// char *OPTELSEIF = "OPTELSEIF"; //TODO - do I need this?
// char *OPTELSE = "OPTELSE"; //TODO - do I need this?
char *ELSEIF = "ELSEIF";
char *ELSEIFSTATEMENT = "ELSEIFSTATEMENT";
char *ELSE = "ELSE";
char *WHILE = "WHILE";
char *END_OF_INPUT = "END_OF_INPUT";
char *KEYWORD = "KEYWORD";
char *BAD_LEX = "BAD_LEX";
char *OPEN_CURL = "OPEN_CURL";
char *CLOSE_CURL = "CLOSE_CURL";
char *QUOTE = "\"";
char *GLUE = "GLUE";
char *ASSIGN_NARRAY = "ASSIGN_NARRAY";
char *ASSIGN_ARRAY = "ASSIGN_ARRAY";
char *ARRAY_INDEX = "ARRAY_INDEX";
char *ARRAY = "ARRAY";
char *CLOSURE = "CLOSURE";
char *BUILTIN = "BUILTIN";
